### ISSUE TITLE
制作台升级为化工厂，会穿模

### ISSUE THREAD

**Issue by Fieyina** [YukkuriC/DSP-BepInEx-Mods#1]
感谢老哥的贡献，很喜欢 mod，不过当前制作台会变成化工厂，有点儿尴尬，我感觉应该可以很容易修改下吗

**Comment by YukkuriC** [comment]
修好了_(:з」∠)_
https://github.com/YukkuriC/DSP-BepInEx-Mods/commit/8c21f49469d419fc709555e469a432592390f138
