### ISSUE TITLE
报错如图

### ISSUE THREAD

**Issue by www925912** [YukkuriC/DSP-BepInEx-Mods#2]
![屏幕截图 2021-02-28 171845](https://user-images.githubusercontent.com/79786927/109413791-37c68f80-79ea-11eb-9107-ec2cf0fc4449.png)

报错如图

**Comment by YukkuriC** [comment]
fixed
https://github.com/YukkuriC/DSP-BepInEx-Mods/commit/402b90dde04839f2ac72db07f0a55eb49c5f72fc
