### ISSUE TITLE
传送带bug

### ISSUE THREAD

**Issue by www925912** [YukkuriC/DSP-BepInEx-Mods#3]
![屏幕截图 2021-02-28 172058](https://user-images.githubusercontent.com/79786927/109414080-ea4b2200-79eb-11eb-891a-8ea5875b1012.png)
图中 的五条传送带一键升级后无法删除和选中，如果升级前和建筑链接 还是正常运行（无法删除和选中），爪子可以取放东西（从虚空中），如果升级后将其链接的建筑删除，此传送带就变成了地表装饰，而且能在上面建造。

**Comment by YukkuriC** [comment]
暂无计划在已有新版本时继续修复流通旧版本产生的bug
